### ISSUE TITLE
Juniper vqfx lab not saving configs into the default directory 

### ISSUE THREAD

**Issue by gwoodwa1** [srl-labs/containerlab#763] opened 2022-02-08 14:50 UTC
When making changes to the Juniper vqfx configuration these are not saved in the default directory. Instead the configuration changes made are lost whenever the containerlab is destroyed. I am unsure if this is a file permissions issue or just something which isn't yet working for these specific devices. I will ask a colleague to try this as well to confirm this is not a local file permissions issue on my side. However, this would seem unlikely since the folders are created without any problems with file permissions. I will report back on my findings unless this is already a known issue around this. I can see the directory structure is in place (below) but the folders are completely empty.
```
gary@gary-MS-7B17:~/container_lab/clab-2L2S_vqfx$ ls
ansible-inventory.yml  leaf1  leaf2  spine1  spine2
```

**Comment by gwoodwa1** [comment] 2022-02-09 06:07
Also using the containerlab save command does not write the configs to the persistent directory.
```
gary@gary-MS-7B17:~/container_lab$ sudo containerlab save --topo vqfx.yml
INFO[0000] Parsing & checking topology file: vqfx.yml   
INFO[0000] saved leaf1 running configuration to startup configuration file 
INFO[0000] saved leaf2 running configuration to startup configuration file 
INFO[0000] saved spine2 running configuration to startup configuration file 
INFO[0000] saved spine1 running configuration to startup configuration file 
```
If I look in the folders they are empty and there are no files created.

**Comment by hellt** [comment] 2022-02-09 10:29
Hi @gwoodwa1 
yes, this is a known issue. vQFX doesn't support config persistency, as this is a VM for which nobody added such functionality.

The `config save` feature should be possible to add rather quickly, if vqfx supports netconf. Do you know if it does?

**Comment by gwoodwa1** [comment] 2022-02-09 12:00
Hi @hellt, Firstly you guys that came up with this deserve full credit for what is a real game changer. I believe the vqfx should support Netconf since Juniper by default allows you to use the same port as SSH i.e. 22. I will set this up and come back to you to confirm.

**Comment by gwoodwa1** [comment] 2022-02-10 08:07
Out of the box with default config, Juniper vqfx does indeed support NETCONF over the standard SSH port 22. Hopefully, this might be enough to get the config persistence enabled (see below).
```
gary@gary-MS-7B17:~/container_lab$ ssh 172.20.20.2 -p 22 -l admin -s netconf
The authenticity of host '172.20.20.2 (172.20.20.2)' can't be established.
ECDSA key fingerprint is SHA256:S5gTisaBW1vp3N2yiMYkQjVzTEbM/DAuFtPNPYrhHno.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '172.20.20.2' (ECDSA) to the list of known hosts.
Password:
<!-- No zombies were killed during the creation of this user interface -->
<!-- user admin, class j-super-user -->
<nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <nc:capabilities>
    <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?scheme=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</nc:capability>
    <nc:capability>http://xml.juniper.net/netconf/junos/1.0</nc:capability>
    <nc:capability>http://xml.juniper.net/dmi/system/1.0</nc:capability>
  </nc:capabilities>
  <nc:session-id>3469</nc:session-id>
</nc:hello>
]]>]]>
```

**Comment by hellt** [comment] 2022-02-10 11:40
ah, sorry, the save functionality is already there in vqfx. when you use `clab save` the running config is saved to startup config.

the problem is though that this startup file is not exposed to a container in any way. meaning that you don't get to see the stratup config in your containerlab host filesystem. The reason is that vqfx is a VM that runs inside a container, so in order to get the file out of a vm you have to use some workarounds, such as keeping the config on an internal ftp/http server. This part is not something that vqfx/vmx has at the moment. Instead of adding it today to vr-vqfx, I'd rather see if someone can add those platforms to `boxen` project.

One workaround that you can use today, is `scp` the saved config from the vqfx if you know the location of the startup config file

**Comment by hellt** [comment] 2022-02-10 18:14
but, if anyone with python skills wants to address this in the https://github.com/hellt/vrnetlab/tree/master/vqfx then I would gladly review/accept this

basically the idea would be to run a process inside the container that will copy (with scp or something similar) a file from vqfx FS to containers FS to a certain path.
That path we will bind mount to container host so that it will be visible in the lab directory

**Comment by gwoodwa1** [comment] 2022-02-10 18:42
Sounds tricky, if that's already been done or similar then it should be a case of follow the yellow brick road. However, it sounds like this is something bespoke and there is no reference model or precedent to follow. I will check the other Juniper virtual products to see if this is the same issue. Since if it works on VMX or cRPD then it may not need the wheel re-invented. If not then I could do it but with some hand holding and support.

**Comment by hellt** [comment] 2022-02-10 19:27
it is custom, because getting files to/from VM is not possible without tricks like that.

Consider the case where you have vqfx VM deployed on your hypervisor with qemu/kvm or EVE-NG/GNS. The same question would pop up - how to get a file from a VM to your hypervisor? VMs do not have bind mounts to propagate a host file to the VM, you would need to copy it out.
Same applies to containerlab, since vqfx is a VM running inside a container.

there is one alternative approach that we used for SR OS - leverage the tftp/ftp/sftp config location. If vqfx can fetch its config from some server, then it can be added the same way we did with SR OS. If it can't though, then we would need to do it the way I explained in my prev. message

**Comment by gwoodwa1** [comment] 2022-02-10 19:45
Absolutely right, I can see the active configuration file is there in the vqfx but the file is not exposed to the container itself. 
```
admin@leaf1> file list /config/juniper.conf.gz 
/config/juniper.conf.gz
{master:0}
admin@leaf1> 
 ```
However, I can see a way forward where we either SCP or SFTP the file over using the shell inside the vqfx. Would this help in terms of copying the method you did for SROS?
 
```
admin@leaf1> start shell 
% sftp
usage: sftp [-1246aCfpqrv] [-B buffer_size] [-b batchfile] [-c cipher]
          [-D sftp_server_path] [-F ssh_config] [-i identity_file] [-l limit]
          [-o ssh_option] [-P port] [-R num_requests] [-S program]
          [-s subsystem | sftp_server] [-JU rt_inst] host
       sftp [user@]host[:file ...]
       sftp [user@]host[:dir[/]]
       sftp -b batchfile [user@]host
% scp
usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [-JU routing_instance]
           [[user@]host1:]file1 ... [[user@]host2:]file2
% 
```

**Comment by hellt** [comment] 2022-02-11 19:59
this helps to get the config in/out the VM, but in SR OS we used a different technique.
In SR OS you can say that you want the VM to find its config on a FTP server, and when the VM boots it will try to fetch the config from this remote location.

I am not sure if VMX has support for remote location of its config... but you can definitely first execute the `clab save` command to save the running to startup and then just copy it with scp to a container

**Comment by gwoodwa1** [comment] 2022-02-14 07:41
I think it's possible to something like this
```
admin@spine1# load override scp://user@127.0.0.1/my_config_dir/spine1.cfg source-address 10.0.0.15 routing-instance default.inet
```
My main problem is finding out the networking from my qfx back to my local machine i.e. which IP do I attach to. When you SSH you use a 172.20.20.x IP but this is of course NATed. Going back to my local machine it must be something else, I am looking into this side but I think the above will be a workable solution.

**Comment by gwoodwa1** [comment] 2022-02-14 09:22
I get the idea of what we are trying to achieve. However, probably missing something here which will make this work. I've add a default route to forward it via 10.0.0.2 which is the container IP. I know this is the container IP because if I SSH to 10.0.0.2 it brings it back to the qfx. In order for SCP to work then I think we would need a different port because the SSH TCP Port 22 mapping will route back to the qfx. It's little on the complicated side but I will keep looking at it. I've installed some more tools into the container so I can see what is going on.

```
admin@spine1> show route 

inet.0: 5 destinations, 5 routes (5 active, 0 holddown, 0 hidden)
+ = Active Route, - = Last Active, * = Both

0.0.0.0/0          *[Static/5] 00:37:18
                    >  to 10.0.0.2 via em0.0
```
```
admin@spine1> traceroute 172.20.20.3 
traceroute to 172.20.20.3 (172.20.20.3), 30 hops max, 40 byte packets
 1  * * *
 2  * * *
```

**Comment by hellt** [comment] 2022-02-14 09:50
yeah, indeed, that is a loop there :D
a `socat` rule defined here basically forwards everything that comes to `container:22` socket towards `127.0.0.1:2022` - https://github.com/hellt/vrnetlab/blob/80bba74d2269eb14215fd4a35e51154644234936/common/vrnetlab.py#L667

then, using the qemu hostfwd rules, this gets routed to `10.0.0.15:22` which is a qemu address - https://github.com/hellt/vrnetlab/blob/80bba74d2269eb14215fd4a35e51154644234936/common/vrnetlab.py#L399

to overcome this I think someone needs to look at the `socat` config options to check if we can run socat in a way that it will only forward packets incoming from eth0 interface towards 127.0.0.1:22, and will not touch packets that come from internal interface (10.0.0.15)

**Comment by gwoodwa1** [comment] 2022-02-14 11:24
Here's my strategy for a solution. I configure the Juniper to use a custom SCP TCP Port e.g. 65022 instead of Port 22. I add an additional socat listener for that port via the vrnetlab.py. I install an SSH server into the container and map that 65022 port into the sshd_config file. If my understanding is correct I would then re-image using that setup instead and re-deploy. When I do the SCP it would be to the 10.0.0.2 address using the 65022 custom port which is the container itself. This will take some working through but I can see a path to success somewhere in all this. Thank you for your pointers so far, it seems we're getting closer.

**Comment by hellt** [comment] 2022-02-14 12:20
that seems doable, but it is a lot of steps to do
I think it might be way easier to fix the socat redirect rule https://github.com/hellt/vrnetlab/blob/80bba74d2269eb14215fd4a35e51154644234936/common/vrnetlab.py#L667

my idea is to restrict this socat rule to act only on packets incoming to a container, and not from the VM.
It seems, what you can do is to try this snippet which configures the socat to bind to eth0 interface and only then forward it to 127.0.0.1:2022:

```python
run_command(
                ["socat", "TCP-LISTEN:22,fork,so-bindtodevice=eth0", "TCP:127.0.0.1:2022"], background=True
            )
```

I hope this will immediately allow for VM to use ssh/scp towards 10.0.0.2:22 as this won't be matched by socat rule and will use the scp/ssh server of a container


PS. you can also do changes in the python file without reimaing the vqfx. You will need to use binds instructions to make the patched `common.py` to be propagated to the container:

```yaml
nodes:
  vqfx:
  binds:
    - common.py:/common.py
```

**Comment by gwoodwa1** [comment] 2022-02-14 13:04
The Socat rule is working as expected so that's great news. The loop is broken so that side is fixed. Next I've installed the SSH-Server from Ubuntu into the container. I am getting an error if I try it from the Juniper vQFX or even locally on the container.
```
admin@leaf1> ssh 10.0.0.2          
ssh_exchange_identification: read: Connection reset by peer
```
This is the output showing the socat rule which you sent across to me which is working.

```
root@leaf1:/# ps -ef             
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 12:42 pts/0    00:00:00 python3 /launch.py --username admin --password admin@
root          17       1  0 12:42 pts/0    00:00:00 socat TCP-LISTEN:22,fork,so-bindtodevice=eth0 TCP:127
root          18       1  0 12:42 pts/0    00:00:00 socat UDP-LISTEN:161,fork UDP:127.0.0.1:2161
root          19       1  0 12:42 pts/0    00:00:00 socat TCP-LISTEN:830,fork TCP:127.0.0.1:2830
root          20       1  0 12:42 pts/0    00:00:00 socat TCP-LISTEN:80,fork TCP:127.0.0.1:2080
root          21       1  0 12:42 pts/0    00:00:00 socat TCP-LISTEN:443,fork TCP:127.0.0.1:2443
root          22       1  0 12:42 pts/0    00:00:00 socat TCP-LISTEN:6022,fork,so-bindtodevice=eth0 TCP:1
root          23       1 34 12:42 pts/0    00:04:10 qemu-system-x86_64 -enable-kvm -display none -machine
root          43       1 12 12:42 pts/0    00:01:32 qemu-system-x86_64 -enable-kvm -display none -machine
root         162       0  0 12:49 pts/1    00:00:00 bash
root         962      17  0 12:54 pts/0    00:00:00 socat TCP-LISTEN:22,fork,so-bindtodevice=eth0 TCP:127
root         964     162  0 12:54 pts/1    00:00:00 ps -ef
````
However, we're definitely making progress here. Just need to find a way of getting past this bit around the SSH key exchange.

**Comment by hellt** [comment] 2022-02-14 13:37
maybe it is easier to act from the container side?
i.e. inside the container to do `scp admin@10.0.0.15:/path/to/saved/config ./`? That way you don't need to have a ssh server inside the container

**Comment by gwoodwa1** [comment] 2022-02-14 14:37
Much better idea (as you mentioned above) is to use scp from the container towards the Juniper. Now I have successfully done that using the 172.20.20.x address with this dummy config file. Note I couldn't write it into the /config directory where the actual config is stored but it works copying into /var/tmp on the vqfx.

```
root@leaf1:/# scp juniper1.conf.gz admin@172.20.20.2:/var/tmp
Password:
juniper1.conf.gz                                                                                   100%    0     0.0KB/s   00:00    
```
I need to do some testing to make the process will work with load overrride but this is looking very workable. I will post back once I have done the testing and proved the whole thing working.

**Comment by gwoodwa1** [comment] 2022-02-15 13:47
Okay so we have a working and tested solution. I will explain what I did in precise detail because there are some things around the edges which will still need to be done.

**Step 1**

added openssh-server into the vqfx docker file so the image has SCP available. Build image so containers all have SSH and SCP. Configuration for openssh-server left with defaults.

**Step 2**

SCP the backup config file from the container to the vQFX using the eth0 172.20.20.x IP address. Suggest using /var/tmp directory due to permissions.
```
root@leaf1:/# scp leaf1_backup.cfg admin@172.20.20.2:/var/tmp
Password:
leaf1_backup.cfg                                                                                     100% 2464     3.9MB/s   00:00    
```
**Step 3**

From inside the container SSH to the vqfx:

```
root@leaf1:/# ssh admin@172.20.20.2
Password:
Last login: Tue Feb 15 03:32:09 2022 from 10.0.0.2
--- JUNOS 19.4R1.10 built 2019-12-19 03:54:05 UTC
{master:0}
```
**Step 4**
Enter configure mode and to the load-override and commit
```
admin@leaf11> configure 
Entering configuration mode
Users currently editing the configuration:
  admin terminal p0 (pid 2448) on since 2022-02-15 03:24:45 UTC, idle 00:08:16
      {master:0}[edit]

{master:0}[edit]
admin@leaf11# load override /var/tmp/leaf1_backup.cfg 
load complete

{master:0}[edit]
admin@leaf11# show | compare 
[edit system]
-  host-name leaf11;
+  host-name leaf10;
[edit system services rest http]
-     port 8082;
+     port 1082;
[edit vlans default]
-   vlan-id 1;
+   vlan-id 2;

{master:0}[edit]
admin@leaf11# commit 
```
**Step 5**

Check the commit is complete
```
admin@leaf11# commit 
configuration check succeeds
commit complete
```
**All Steps Completed**
The backup file in /var/tmp has been successfully loaded and overwrote the current running configuration

**Comment by gwoodwa1** [comment] 2022-02-15 13:50
The process above is how we achieve the overall steps. You're right that going from the container to the Juniper is going to be much easier to work with than the other way around. However, there is a wrap needed to finish this off. For example, we need the persistent configuration directory to be mapped into the container then a script needs to look for any config files present and load these using the process which I went through. This can only be done once the container is fully booted I would assume unless there is a way we can poke the config stanza into the startup config as the container is launched. Anyways we have a process but just need to tie up the loose ends on implementation with containerlab.

**Comment by hellt** [comment] 2022-05-09 05:59
Closing this one as there is no immediate fix for that at the moment
We would need a way for vrnetlab/boxen to work with config exposure to the host

**Closed by hellt** 2022-05-09 05:59 UTC
Labels: juniper

**Comment by hellt** [comment] 2022-05-17 11:00
In #889 @crankynetman added support for user provided configs for vqfx
Similar approach could have been implemented to a `save` command to make changes to persist
