### ISSUE TITLE
Ceos interfaces are missing

### ISSUE THREAD

**Issue by Zulzig** [srl-labs/containerlab#2057] opened 2024-06-01 15:07 UTC
Hi,

I’m experiencing a problem with the ceos lab; I attempted to set up a basic topology, but some devices only have management interfaces and no additional ones. I discovered a similar issue that appears to have been resolved.

containerlab version:
```  
    version: 0.54.2
     commit: 9ecdf0e2
       date: 2024-04-11T12:01:05Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.54/#0542
```

docker version:
```
  $ docker --version
  Docker version 26.1.3, build b72abbb
```

OS version:
```
  $ lsb_release -a
  LSB Version:	n/a
  Distributor ID:	Fedora
  Description:	Fedora Linux 38 (Workstation Edition)
  Release:	38
  Codename:	n/a
```

```
$ docker images
REPOSITORY                    TAG       IMAGE ID       CREATED        SIZE
ceos                          4.31.1F   03781fb6f41d   13 days ago    2.03GB
vrnetlab/vr-fortigate         7.4.4.F   2308a8db7d14   2 weeks ago    1.11GB
vrnetlab/vr-pan               11.0.0    74eef99e8499   2 weeks ago    4.56GB
```

device ko, all interfaces are missing
```
#sh int status
Port       Name   Status       Vlan     Duplex Speed  Type         Flags Encapsulation
Ma0               connected    routed   a-full a-1G   10/100/1000                    

#sh run | s interface
interface Management0
   vrf MGMT
   ip address 172.16.100.22/24
```

device ko, two interfaces are missing
```
#sh int status
Port       Name   Status       Vlan     Duplex Speed  Type            Flags Encapsulation
Et1               connected    1        full   1G     EbraTestPhyPort                   
Et2               connected    1        full   1G     EbraTestPhyPort                   
Et3               connected    1        full   1G     EbraTestPhyPort                   
Et4               connected    1        full   1G     EbraTestPhyPort                   
Ma0               connected    routed   a-full a-1G   10/100/1000                       

#sh run | s interface
interface Ethernet1
interface Ethernet2
interface Ethernet3
interface Ethernet4
interface Management0
   vrf MGMT
   ip address 172.16.100.23/24
```

device ok
```
#sh int status
Port       Name   Status       Vlan     Duplex Speed  Type            Flags Encapsulation
Et1               connected    1        full   1G     EbraTestPhyPort                   
Et2               connected    1        full   1G     EbraTestPhyPort                   
Et3               connected    1        full   1G     EbraTestPhyPort                   
Et4               connected    1        full   1G     EbraTestPhyPort                   
Et5               connected    1        full   1G     EbraTestPhyPort                   
Et6               connected    1        full   1G     EbraTestPhy                  

#sh run | s interface
interface Ethernet1
interface Ethernet2
interface Ethernet3
interface Ethernet4
interface Ethernet5
interface Ethernet6
interface Management0
   vrf MGMT
   ip address 172.16.100.17/24
```
logs
```
INFO[0001] Created link: ceos-01:eth2 <--> ceos-02:et3 
INFO[0001] Running postdeploy actions for Arista cEOS 'ceos-01.helios.lab' node 

```

**Comment by hellt** [comment] 2024-06-01 15:13
can be a resource issue
you can enter the container's shell of a node that is missing interfaces and check if `ethX` interfaces are there with `ip link`
If they are there, then it is ceos that failed to identify the available interfaces, and this is often due to resource shortage

**Comment by Zulzig** [comment] 2024-06-01 15:18
Hi hellt,

Thank for your feedback
> can be a resource issue you can enter the container's shell of a node that is missing interfaces and check if `ethX` interfaces are there with `ip link` If they are there, then it is ceos that failed to identify the available interfaces, and this is often due to resource shortage

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: cpu: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:73:f0:4c:46 brd ff:ff:ff:ff:ff:ff
3: fabric: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 10000 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:73:f0:4c:46 brd ff:ff:ff:ff:ff:ff
4: fabric1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 10000 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:73:f0:4c:46 brd ff:ff:ff:ff:ff:ff
5: fabric2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 10000 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:73:f0:4c:46 brd ff:ff:ff:ff:ff:ff
6: fabric3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 10000 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:73:f0:4c:46 brd ff:ff:ff:ff:ff:ff
7: mirror0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether e6:da:af:3a:fe:2c brd ff:ff:ff:ff:ff:ff
8: mirror1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether f6:03:29:6d:e4:08 brd ff:ff:ff:ff:ff:ff
9: mirror2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether de:61:89:cd:84:c7 brd ff:ff:ff:ff:ff:ff
10: mirror3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 62:7e:63:8f:76:0f brd ff:ff:ff:ff:ff:ff
11: fwd0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:1c:73:f0:4c:46 brd ff:ff:ff:ff:ff:ff
12: arpsnoop: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 26:4b:c0:8b:fa:fc brd ff:ff:ff:ff:ff:ff
13: arpinject: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fa:65:60:0f:b1:cd brd ff:ff:ff:ff:ff:ff
91: eth0@if92: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:10:64:17 brd ff:ff:ff:ff:ff:ff link-netnsid 0
116: et1@if115: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9214 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:a2:e5:49 brd ff:ff:ff:ff:ff:ff link-netnsid 1
124: et2@if123: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9214 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:4f:2c:ae brd ff:ff:ff:ff:ff:ff link-netnsid 3
129: et3@if130: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9214 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:bd:5b:53 brd ff:ff:ff:ff:ff:ff link-netnsid 2
133: et4@if134: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9214 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:45:10:1c brd ff:ff:ff:ff:ff:ff link-netnsid 2
```

**Comment by hellt** [comment] 2024-06-01 15:25
How does your topology look like?

**Comment by Zulzig** [comment] 2024-06-01 15:42
![lab](https://github.com/srl-labs/containerlab/assets/3287637/a9d67176-e168-4406-bbe8-21864e08752a)
A red circle indicates devices that are missing interfaces.

**Comment by Zulzig** [comment] 2024-06-01 15:58
I deleted the lab and the directory and recreated them, which seems to have resolved my issue. Could there be a problem with my operating system?
now:
```
access-01>sh int status
Port       Name   Status       Vlan     Duplex Speed  Type            Flags Encapsulation
Et1               connected    1        full   1G     EbraTestPhyPort                   
Et2               connected    1        full   1G     EbraTestPhyPort                   
Ma0   
```
before:
```
access-01>en
access-01#sh int status
Port       Name   Status       Vlan     Duplex Speed  Type         Flags Encapsulation
Ma0

**Comment by hellt** [comment] 2024-06-01 17:46
could be. Since this is resolved on its own I am closing this
feel free to reopen if you have a reproduction with the source topology file

**Closed by hellt** 2024-06-01 17:46 UTC
