### ISSUE TITLE
Container interfaces connected to host interfaces via `macvlan`

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1393] opened 2023-05-16 19:43 UTC
To enable use cases where containers can connect to the external world using host interfaces the following options can be considered:

1. Use a linux bridge to bridge container's veth interface with host's interface.
    This mode has been supported by containerlab since the beginning.
    
    <img width="1201" alt="image" src="https://github.com/srl-labs/containerlab/assets/5679861/cccd4054-fc3a-4b0a-8e55-71e51162d96b">
2. Using macvlan device type where a macvlan device is multiplexed on a MAC level with the host's interface

This issue tracks the development for 2nd option where a macvlan device should be added to container's namespace and coupled with the hosts interface.

The following material may assist in the implementation:

- http://networkstatic.net/configuring-macvlan-ipvlan-linux-networking/

**Comment by ipspace** [comment] 2023-05-17 05:51
@hellt: Thanks for opening this feature request ;)

The beauty of using macvlan or macvtap interfaces (two different drivers doing almost the same thing -- welcome to Linux networking) is that they just work without the user having to configure anything.

I would prefer having the option to use one or the other; the difference (from high-level perspective, using CLI commands) is just the `type` keyword in the `ip link add` command. **macvlan** is used by Docker whereas **macvtap** is used by KVM/libvirt. Supporting both would get rid of any potential incompatibility issues.

Configuring this functionality could be as easy as supporting "macvtap:uplink" and "macvlan:uplink" as the second endpoint in **links** list.

FWIW, I'm tracking the same challenge in https://github.com/ipspace/netlab/issues/809. Unfortunately, while it's possible to create macvlan/macvtap container interface after `containerlab deploy` completes, Arista EOS (for example) doesn't want to recognize the new interface (Linux/FRR works like a charm), so the only way to have a consistent implementation is to do it in containerlab.

**Comment by ipspace** [comment] 2023-05-17 05:58
Also: the Go netlink library used by _containerlab_ already contains `Macvlan` and `Macvtap` types, that could be used instead of `Veth` type to create the interface. The whole wiring logic would have to be changed though as there is no other end of the **macvlan** or **macvtap** interface.

**Comment by steiler** [comment] 2023-05-17 06:41
This is a duplicate of #475 as far as I can tell.
Lets maybe close #475, since we seem to have some more details here already.

**Comment by hellt** [comment] 2023-05-17 07:09
@steiler this is similar, but different. #475 is about using macvlan driver for docker network (management), and therefore it concerns exposing management interface via a host interface.

This feature request is about non-management datapath interfaces which are not connected to docker network nor managed by docker

**Comment by steiler** [comment] 2023-05-17 07:21
alright, sorry my bad.

**Closed** 2023-07-26 11:52 UTC
Labels: enhancement, fix available
